-- Database-wide integrity gap discovered while debugging "Transaction silently rolled
-- back... UnexpectedRollbackException" / "AssertionFailure: null identifier" on
-- POST /lab/{labId}/add-patient: the `patients` table (and, on inspection, nearly every
-- other core table) has NO primary key constraint and NO identity/sequence default on its
-- id column. Existing rows have clean sequential ids (proving these tables did have proper
-- identity columns at some point), but with no DB-side default, every INSERT relying on
-- Hibernate's GenerationType.IDENTITY strategy inserts a NULL id, gets NULL back from
-- `RETURNING`, and Hibernate throws exactly this assertion. Reads/joins were unaffected
-- (no PK needed for SELECT), which is why this was invisible until the first new-row INSERT
-- was attempted against each table.
--
-- Fix: for every affected single-column surrogate-key table, add GENERATED BY DEFAULT AS
-- IDENTITY starting after the current max id (so no collision with existing rows), then add
-- the PRIMARY KEY constraint. UUID-keyed tables (refresh_tokens, lab_audit_logs) only need
-- the PRIMARY KEY restored - the application already generates their UUIDs itself.
--
-- Not touched: daily_lab_stats and lab_entity_sequence use intentional composite keys
-- (lab_id, stat_date) / (lab_id, entity_name), not surrogate ids - not part of this issue.
-- Pure join/junction tables (lab_billing, lab_doctors, lab_patients, users_roles, etc.) are
-- also out of scope here; they don't rely on IDENTITY generation and aren't causing the
-- reported failure.

DO $$
DECLARE
    rec RECORD;
    start_val BIGINT;
    has_default BOOLEAN;
BEGIN
    FOR rec IN
        SELECT * FROM (VALUES
            ('patients', 'patient_id'),
            ('labs', 'lab_id'),
            ('users', 'user_id'),
            ('doctors', 'doctor_id'),
            ('health_packages', 'package_id'),
            ('insurance', 'insurance_id'),
            ('billing', 'billing_id'),
            ('billing_transaction', 'transaction_id'),
            ('tests', 'test_id'),
            ('lab_report', 'report_id'),
            ('patient_visits', 'visit_id'),
            ('roles', 'role_id'),
            ('modules', 'module_id'),
            ('otps', 'id'),
            ('password_reset_rate_limits', 'id'),
            ('password_reset_tokens', 'id'),
            ('report_role_settings', 'id'),
            ('report_settings', 'id'),
            ('sample_entity', 'sample_id'),
            ('super_admin_test_pricelistentity', 'test_id'),
            ('super_admin_test_referance', 'test_reference_id'),
            ('test_discount', 'discount_id'),
            ('test_reference', 'test_reference_id'),
            ('verification_tokens', 'id')
        ) AS t(table_name, id_column)
    LOOP
        EXECUTE format('SELECT COALESCE(MAX(%I), 0) + 1 FROM %I', rec.id_column, rec.table_name)
            INTO start_val;

        EXECUTE format(
            'ALTER TABLE %I ALTER COLUMN %I SET NOT NULL',
            rec.table_name, rec.id_column
        );

        SELECT EXISTS (
            SELECT 1 FROM pg_attrdef d
            JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
            WHERE d.adrelid = rec.table_name::regclass AND a.attname = rec.id_column
        ) INTO has_default;

        -- Some tables (e.g. otps) already have a working sequence default and only lost
        -- their PRIMARY KEY constraint - don't touch identity generation there, just add the PK.
        IF NOT has_default THEN
            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                rec.table_name, rec.id_column, start_val
            );
        END IF;

        EXECUTE format(
            'ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY (%I)',
            rec.table_name, rec.table_name || '_pkey', rec.id_column
        );
    END LOOP;
END $$;

-- UUID-keyed tables: restore PRIMARY KEY only, no identity needed.
ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE lab_audit_logs ADD CONSTRAINT lab_audit_logs_pkey PRIMARY KEY (id);
